#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
[tasks.check-cross-installed]
workspace = false
script = '''
#/usr/bin/env bash

which cross >/dev/null && exit 0

echo "!!!! ERROR: 'cross' binary not found. install with 'cargo install cross'. !!!!!"
exit 1
'''

[tasks.build-dhcp-server]
category = "Build"
description = "Build dhcp-server for aarch architecture."
workspace = false
script = '''
docker run --rm -v $REPO_ROOT:/nico --user $(id -u):$(id -g) \
    --env CARGO_HOME=/cargo \
    -v $CARGO_HOME:/cargo \
    build-artifacts-container-cross-aarch64:latest \
    "cargo" \
    "build" \
    "--release" \
    "--target=aarch64-unknown-linux-gnu" \
    "--bin" \
    "nico-dhcp-server"
docker run --rm -v $REPO_ROOT:/nico --user $(id -u):$(id -g) build-artifacts-container-cross-aarch64:latest "aarch64-linux-gnu-strip" \
    "/nico/target/aarch64-unknown-linux-gnu/release/nico-dhcp-server" \
'''
dependencies = [
  { name = "check-cargo-home-set", path = "${REPO_ROOT}" },
  { name = "build-cross-docker-image", path = "${REPO_ROOT}" },
]

[tasks.build-dhcp-server-ci]
category = "Build"
workspace = false
command = "cargo"
args = ["build", "--release", "--bin", "nico-dhcp-server"]
