#!/usr/bin/env bash
# This is called from parallel CLI and creates a docker task for each component passed
# Each component gets its own cargo cache and cargo_target_dir

# Check if CONTEXT is set to k3s
if [ "$CONTEXT" == "k3s" ]; then
  IMAGE_NAME="build-container-localdev"
else
  IMAGE_NAME="registry.minikube/build-container:latest"
fi

# get the first word from this string
COMPONENT=`echo $1 | cut -d" " -f1`

docker run --rm -v $REPO_ROOT:/nico \
  -e CARGO_TARGET_DIR=/target/$COMPONENT \
  -e CARGO_HOME=/cache/cargo/$COMPONENT \
  -e SCCACHE_DIR=/cache/sccache \
  -e USER=$USER \
  -v $REPO_ROOT/.skaffold/target:/target \
  -v $REPO_ROOT/.skaffold/cache:/cache \
  --user $(id -u):$(id -g) \
  --add-host urm.nvidia.com:10.124.92.246 \
  $IMAGE_NAME $1

