#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
REPO_ROOT = { script = [
  "dirname $(cargo locate-project --message-format plain --workspace)",
] }

[tasks.build-component-local]
category = "Build"
description = "compile nico package"
workspace = false
script = '''

echo "building ${NICO_PROFILE}/${NICO_ARCH} of ${NICO_CRATE}"

if [ "${NICO_PROFILE}" = "release" ]
then
  profile_arg="--release"
fi
pkg_args="${pkg_args} -p ${NICO_CRATE}"

cargo build ${profile_arg} --target=${NICO_ARCH}-unknown-linux-gnu ${pkg_args}
'''

[tasks.build-component-in-container]
category = "Build"
description = "compile nico package x86_64"
workspace = false
script = '''

echo "building ${NICO_PROFILE}/${NICO_ARCH} of ${NICO_CRATE}"

if [ "${NICO_PROFILE}" = "release" ]
then
  profile_arg="--release"
fi

case "${NICO_ARCH}" in
  "x86_64")
    IMAGE_NAME="urm.nvidia.com/swngc-ngcc-docker-local/nico/nico/x86-64/build-container:latest"
    ;;
  "aarch64")
    IMAGE_NAME="build-artifacts-container-cross-aarch64:latest"
    ;;
  *)
    echo "Unknown architecture"
    exit 1
    ;;
esac

pkg_args="${pkg_args} -p ${NICO_CRATE}"

docker run \
    --rm \
    --workdir /nico \
    --env CARGO_HOME=/cargo \
    --user $(id -u):$(id -g) \
    --volume $REPO_ROOT:/nico \
    --volume $CARGO_HOME:/cargo \
    $IMAGE_NAME \
    cargo build ${profile_arg} --target=${NICO_ARCH}-unknown-linux-gnu ${pkg_args}

  if [ "${NICO_PROFILE}" = "release" ] && [ "${NICO_ARCH}" = "x86_64" ]
  then
  docker run \
    --rm \
    --user $(id -u):$(id -g) \
    --volume $REPO_ROOT:/nico \
    urm.nvidia.com/swngc-ngcc-docker-local/nico/nico/x86-64/build-container:latest \
    x86_64-linux-gnu-strip /nico/target/x86_64-unknown-linux-gnu/release/nico-scout
  else
    echo "Skipping strip of sysmbols in profile ${NICO_PROFILE}"
  fi
'''
dependencies = [
  { name = "build-x86-build-container", path = "${REPO_ROOT}" },
  { name = "build-cross-docker-image", path = "${REPO_ROOT}" },
]
