/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
use std::path::PathBuf;

use tonic_client_wrapper::codegen;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    // Write generated code to OUT_DIR rather than back into the source tree.
    // Consumers pull these in via:
    // `include!(concat!(env!("OUT_DIR"), "/X.rs"))` in `src/protos/mod.rs`
    let autogenerated_rust_output_directory = out_dir.clone();
    // The reflection path is part of the output directory (which might be debug or release),
    // so that different builds get a different binary file and concurrent builds don't collide
    let reflection = out_dir.join("nico.bin");

    tonic_prost_build::configure()
        .file_descriptor_set_path(reflection)
        .type_attribute(
            ".google.protobuf.Timestamp",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            ".nico.DeletedFilter",
            "#[cfg_attr(feature = \"cli\", derive(clap::ValueEnum))]",
        )
        .type_attribute(
            ".nico.DpuMode",
            "#[cfg_attr(feature = \"cli\", derive(clap::ValueEnum))]",
        )
        .type_attribute(
            ".nico.DpuMode",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .extern_path(".google.protobuf.Duration", "crate::Duration")
        .extern_path(".google.protobuf.Timestamp", "crate::Timestamp")
        .extern_path(".common.DomainId", "::nico_uuid::domain::DomainId")
        .extern_path(".common.DpaInterfaceId", "::nico_uuid::dpa_interface::DpaInterfaceId")
        .extern_path(".common.IBPartitionId", "::nico_uuid::infiniband::IBPartitionId")
        .extern_path(".common.InstanceId", "::nico_uuid::instance::InstanceId")
        .extern_path(".common.MachineId", "::nico_uuid::machine::MachineId")
        .extern_path(".common.MachineInterfaceId", "::nico_uuid::machine::MachineInterfaceId")
        .extern_path(".common.NetworkPrefixId", "::nico_uuid::network::NetworkPrefixId")
        .extern_path(".common.NetworkSegmentId", "::nico_uuid::network::NetworkSegmentId")
        .extern_path(".common.PowerShelfId", "::nico_uuid::power_shelf::PowerShelfId")
        .extern_path(".common.RackId", "::nico_uuid::rack::RackId")
        .extern_path(".common.RackProfileId", "::nico_uuid::rack::RackProfileId")
        .extern_path(".common.NVLinkPartitionId", "::nico_uuid::nvlink::NvLinkPartitionId")
        .extern_path(".common.NVLinkLogicalPartitionId", "::nico_uuid::nvlink::NvLinkLogicalPartitionId")
        .extern_path(".common.NVLinkDomainId", "::nico_uuid::nvlink::NvLinkDomainId")
        .extern_path(".common.RemediationId", "nico_uuid::dpu_remediations::RemediationId")
        .extern_path(".common.SwitchId", "::nico_uuid::switch::SwitchId")
        .extern_path(".common.VpcId", "::nico_uuid::vpc::VpcId")
        .extern_path(".common.VpcPeeringId", "::nico_uuid::vpc_peering::VpcPeeringId")
        .extern_path(".common.VpcPrefixId", "::nico_uuid::vpc::VpcPrefixId")
        .extern_path(".common.ComputeAllocationId", "::nico_uuid::compute_allocation::ComputeAllocationId")
        .extern_path(".common.OperatingSystemId", "::nico_uuid::operating_system::OperatingSystemId")
        .extern_path(".common.IpxeTemplateId", "::nico_uuid::ipxe_template::IpxeTemplateId")
        .extern_path(".common.MachineValidationId", "::nico_uuid::machine_validation::MachineValidationId")
        .extern_path(".measured_boot.MeasurementSystemProfileId", "::nico_uuid::measured_boot::MeasurementSystemProfileId")
        .extern_path(".measured_boot.MeasurementSystemProfileAttrId", "::nico_uuid::measured_boot::MeasurementSystemProfileAttrId")
        .extern_path(".measured_boot.MeasurementBundleId", "::nico_uuid::measured_boot::MeasurementBundleId")
        .extern_path(".measured_boot.MeasurementBundleValueId", "::nico_uuid::measured_boot::MeasurementBundleValueId")
        .extern_path(".measured_boot.MeasurementReportId", "::nico_uuid::measured_boot::MeasurementReportId")
        .extern_path(".measured_boot.MeasurementReportValueId", "::nico_uuid::measured_boot::MeasurementReportValueId")
        .extern_path(".measured_boot.MeasurementJournalId", "::nico_uuid::measured_boot::MeasurementJournalId")
        .extern_path(".measured_boot.MeasurementApprovedMachineId", "::nico_uuid::measured_boot::MeasurementApprovedMachineId")
        .extern_path(".measured_boot.MeasurementApprovedProfileId", "::nico_uuid::measured_boot::MeasurementApprovedProfileId")
        .include_file("prost_common.rs")
        .type_attribute(".health", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            ".machine_discovery",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            ".site_explorer",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            ".mlx_device",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.AdminForceDeleteMachineRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.AdminForceDeleteMachineResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.ClientSecretBasic", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(".dns", "#[derive(serde::Serialize)]")
        .type_attribute("nico.FabricManagerConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.FabricManagerStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.FlatInterfaceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.FlatInterfaceIpv6Config", "#[derive(serde::Serialize)]")
        .type_attribute("nico.InstanceInterfaceIpv6Config", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "nico.InstanceInterfaceConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.InstanceInterfaceConfig.network_details",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.InstanceIBInterfaceConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("nico.InstanceUpdateStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.InstanceNetworkConfig", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.InstanceInfinibandConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("nico.InstanceStorageConfig", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.IpxeTemplateParameter",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.IpxeTemplateArtifact",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.IpxeTemplate",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.IpxeTemplateArtifactCacheStrategy",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("nico.TenantConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.InstanceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.InstanceDpuExtensionServicesConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.InstanceDpuExtensionServiceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.ManagedHostDpuExtensionServiceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.DpuExtensionService", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceVersionInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceType", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceIdList", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceCredential", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceCredential.type", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.UsernamePassword", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceStatusObservation", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceComponent", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceStatus", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceObservability", "#[derive(serde::Serialize, serde::Deserialize)]")        
        .type_attribute("nico.DpuExtensionServiceObservabilityConfigPrometheus", "#[derive(serde::Serialize, serde::Deserialize)]") 
        .type_attribute("nico.DpuExtensionServiceObservabilityConfigLogging", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceObservabilityConfig.config", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceObservabilityConfig", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.DpuExtensionServiceObservability.configs", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.InstanceNVLinkConfig", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("nico.InstanceNVLinkGpuConfig", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("nico.InstanceNVLinkStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.InstanceNVLinkGpuStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkPartition", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkPartitionGpuStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkLogicalPartition", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkLogicalPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkLogicalPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkLogicalPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkLogicalPartitionGpuStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.MachineNVLinkGpuStatusObservation", "#[derive(serde::Serialize)]")
        .type_attribute("nico.MachineNVLinkStatusObservation", "#[derive(serde::Serialize)]")
        .type_attribute("common.NVLinkDomainId", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NvlinkNmxcEndpoint", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.NvlinkNmxcEndpointList", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "nico.DeleteNvlinkNmxcEndpointRequest",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("common.NVLinkLogicalPartitionId", "#[derive(serde::Serialize)]")
        .type_attribute("common.NVLinkPartitionId", "#[derive(serde::Serialize)]")
        .type_attribute("nico.MachineNVLinkInfo", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLinkGpu", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.InstanceInterfaceStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.InstanceIBInterfaceStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.InstanceNetworkStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.InstanceInfinibandStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.InstanceStorageStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.InstanceDpuExtensionServicesStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.InstanceDpuExtensionServiceStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.InstanceTenantStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.InstanceStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.Instance", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.Metadata",
            "#[derive(serde::Serialize, serde::Deserialize, Eq)]",
        )
        .type_attribute(
            "nico.Label",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "nico.LifecycleStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.InstancePhoneHomeLastContactRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.InstancePhoneHomeLastContactResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.InstanceList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.Machine", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.MachineCapabilitiesSet",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.MachineCapabilityAttributesCpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.MachineCapabilityAttributesGpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.MachineCapabilityAttributesMemory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.MachineCapabilityAttributesStorage",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.MachineCapabilityAttributesNetwork",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.MachineCapabilityAttributesInfiniband",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.MachineCapabilityAttributesDpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.MachineList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.MachineEvent", "#[derive(serde::Serialize)]")
        .type_attribute("nico.MachineInterface", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.InfinibandStatusObservation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.MachineIbInterface", "#[derive(serde::Serialize)]")
        .type_attribute("nico.MachineState", "#[derive(serde::Serialize)]")
        .type_attribute("nico.MachineArchitecture", "#[derive(serde::Serialize)]")
        .type_attribute("nico.MachineInventory", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.MachineInventorySoftwareComponent",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.HealthReportEntry", "#[derive(serde::Serialize)]")
        .type_attribute("nico.HealthSourceOrigin", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            "nico.ManagedHostNetworkConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.ManagedHostNetworkConfigResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.RoutingProfile",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.PrefixFilterPolicyEntry",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.TrafficInterceptConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.TrafficInterceptBridging", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NetworkPrefix", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NetworkPrefixEvent", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NetworkSegmentConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NetworkSegmentStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NetworkSegment", "#[derive(serde::Serialize)]")
        .type_attribute("nico.IBPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.IBPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.IBPartition", "#[derive(serde::Serialize)]")
        .type_attribute("nico.IBPartitionIdList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.IBPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.PowerOptionResponse",
                        "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("nico.PowerOptions",
                        "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            "nico.InlineIpxe",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("nico.NetworkSegmentList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.InstanceOperatingSystemConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.InstanceOperatingSystemConfig.variant",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.OperatingSystem",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "nico.OperatingSystemList",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "nico.OperatingSystemType",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("nico.InterfaceList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.NetworkSegmentStateHistory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.RackStateHistory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.Tenant", "#[derive(serde::Serialize)]")
        .type_attribute("nico.TenantContent", "#[derive(serde::Serialize)]")
        .type_attribute("nico.TenantList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.TenantKeyset", "#[derive(serde::Serialize)]")
        .type_attribute("nico.TenantKeysetContent", "#[derive(serde::Serialize)]")
        .type_attribute("nico.TenantKeysetList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.TenantKeysetIdentifier",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.TenantPublicKey", "#[derive(serde::Serialize)]")
        .type_attribute("nico.TenantKeySetList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.VpcResourceState", "#[derive(serde::Serialize)]")
        .type_attribute("nico.MachineBootOverride", "#[derive(serde::Serialize)]")
        .type_attribute("nico.ConnectedDevice", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NetworkDevice", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NetworkTopologyData", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.InstanceInterfaceStatusObservation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.FabricInterfaceData", "#[derive(serde::Serialize)]")
        .type_attribute("nico.LinkData", "#[derive(serde::Serialize)]")
        .type_attribute("nico.DpuNetworkStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.LastDhcpRequest", "#[derive(serde::Serialize)]")
        .type_attribute("nico.ResourcePool", "#[derive(serde::Serialize)]")
        .type_attribute("nico.DpaInterface", "#[derive(serde::Serialize)]")
        .type_attribute("nico.DpaInterfaceList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.Vpc", "#[derive(serde::Serialize)]")
        .type_attribute("nico.VpcStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.VpcList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.StorageClusterAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.VpcPrefix", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.VpcPrefixConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.VpcPrefixStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.VpcPeering", "#[derive(serde::Serialize)]")
        .type_attribute("nico.VpcPeeringList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.StateHistoryRecord",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.StorageCluster", "#[derive(serde::Serialize)]")
        .type_attribute("nico.StoragePoolAttributes", "#[derive(serde::Serialize)]")
        .type_attribute("nico.StoragePool", "#[derive(serde::Serialize)]")
        .type_attribute("nico.StorageVolumeStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.StorageVolumeAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.StorageVolume", "#[derive(serde::Serialize)]")
        .type_attribute("nico.Switch", "#[derive(serde::Serialize)]")
        .type_attribute("nico.SwitchConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.SwitchList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.SwitchStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.DeleteStoragePoolRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.ListStoragePoolRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.ListStoragePoolResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.DeleteStorageVolumeRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.ListStorageVolumeRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.ListStorageVolumeResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.OsImageAttributes", "#[derive(serde::Serialize)]")
        .type_attribute("nico.OsImage", "#[derive(serde::Serialize)]")
        .type_attribute("nico.ListOsImageRequest", "#[derive(serde::Serialize)]")
        .type_attribute("nico.ListOsImageResponse", "#[derive(serde::Serialize)]")
        .type_attribute("DeleteOsImageRequest", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.MachineDiscoveryInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "common.UUID",
            "#[derive(Ord, PartialOrd, serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.MachineDiscoveryInfo.discovery_data",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.DhcpDiscovery",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.UserRoles",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.BMCRequestType",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "nico.BmcInfo",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "nico.bmc_meta_data_update_request.DataItem",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "DataItem",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "bmc_meta_data_update_request",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "BMCMetaDataUpdateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "ControllerStateReason",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("ControllerStateSourceReference", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            "RuntimeConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("StateSla", "#[derive(serde::Serialize)]")
        .type_attribute(
            "BuildInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("MachineValidationResultList", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationResult", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationRunList", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationRun", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedHostNic", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedHostNic", "#[derive(serde::Deserialize)]")
        .type_attribute("HostLifecycleProfile", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ExpectedMachine", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedPowerShelf", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedSwitch", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedRack", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedMachineList", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedPowerShelfList", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedSwitchList", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedRackList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "TpmCaCertDetail",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaCertDetailCollection",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmEkCertStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmEkCertStatusCollection",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaAddedCaStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaCertId",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("MachineValidationState", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationCompleted", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationInProgress", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationStarted", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "MachineValidationExternalConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestUpdateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestAddRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestsGetRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestUpdateRequest.Payload",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.RedfishBrowseResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroup",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupSource",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupRuleDirection",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupRuleProtocol",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupRuleAction",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupRuleAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .field_attribute(
            "nico.NetworkSecurityGroupRuleAttributes.direction",
            "#[serde(deserialize_with = \"NetworkSecurityGroupRuleDirection::from_string\", serialize_with = \"NetworkSecurityGroupRuleDirection::serialize_from_enum_i32\")]",
        )
        .field_attribute(
            "nico.NetworkSecurityGroupRuleAttributes.protocol",
            "#[serde(deserialize_with = \"NetworkSecurityGroupRuleProtocol::from_string\", serialize_with = \"NetworkSecurityGroupRuleProtocol::serialize_from_enum_i32\")]",
        )
        .field_attribute(
            "nico.NetworkSecurityGroupRuleAttributes.action",
            "#[serde(deserialize_with = \"NetworkSecurityGroupRuleAction::from_string\", serialize_with = \"NetworkSecurityGroupRuleAction::serialize_from_enum_i32\")]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupRuleAttributes.source_net",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupRuleAttributes.source_net",
            "#[serde(rename_all=\"snake_case\")]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupRuleAttributes.destination_net",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupRuleAttributes.destination_net",
            "#[serde(rename_all=\"snake_case\")]",
        )
        .type_attribute(
            "nico.InstanceNetworkRestrictions",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.FlatInterfaceNetworkSecurityGroupConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.ResolvedNetworkSecurityGroupRule",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupAttachments",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.NetworkSecurityGroupPropagationObjectStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("Sku", "#[derive(serde::Serialize, serde::Deserialize)]")
        .field_attribute("Sku.schema_version", "#[serde(default)]")
        .field_attribute("Sku.associated_machine_ids", "#[serde(default)]")
        .type_attribute("SkuList", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "SkuComponents",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentChassis",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentCpu",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "common.SwitchId",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "SkuComponentGpu",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentMemory",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentInfinibandDevices",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentEthernetDevices",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentStorage",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .field_attribute("SkuComponentStorage.vendor", "#[serde(default)]")
        .field_attribute("SkuComponentStorage.capacity_mb", "#[serde(default)]")
        .type_attribute(
            "SkuComponentTpm",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("SkuId", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "SkuStatus",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("nico.RackFirmware", "#[derive(serde::Serialize)]")
        .type_attribute("nico.RackFirmwareList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.RackFirmwareHistoryRecord", "#[derive(serde::Serialize)]")
        .type_attribute("nico.RackFirmwareHistoryRecords", "#[derive(serde::Serialize)]")
        .type_attribute("nico.RackFirmwareHistoryResponse", "#[derive(serde::Serialize)]")
        .type_attribute("common.RackHardwareType", "#[derive(serde::Serialize)]")
        .type_attribute("nico.RackCapabilitiesSet", "#[derive(serde::Serialize)]")
        .type_attribute("nico.RackCapabilityCompute", "#[derive(serde::Serialize)]")
        .type_attribute("nico.RackCapabilitySwitch", "#[derive(serde::Serialize)]")
        .type_attribute("nico.RackCapabilityPowerShelf", "#[derive(serde::Serialize)]")
        .type_attribute("nico.RackProfile", "#[derive(serde::Serialize)]")
        .type_attribute("nico.GetRackProfileResponse", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.MachineHardwareInfoGpu",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.ManagedHostQuarantineState",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "nico.ManagedHostQuarantineMode",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("nico.AppliedRemediationIdList", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("nico.AppliedRemediationId", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("nico.AppliedRemediationList", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("nico.AppliedRemediation", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("nico.RemediationList", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("nico.Remediation", "#[derive(serde::Deserialize, serde::Serialize)]")
        .field_attribute("machine_discovery.BlockDevice.device_type", "#[serde(default)]")
        .field_attribute("machine_discovery.NvmeDevice.serial", "#[serde(default)]")
        .type_attribute(
            "nico.InstanceTypeAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.InstanceType",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.InstanceTypeAllocationStats",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .field_attribute(
            "nico.InstanceTypeMachineCapabilityFilterAttributes.capability_type",
            "#[serde(deserialize_with = \"MachineCapabilityType::from_string\", serialize_with = \"MachineCapabilityType::serialize_from_enum_i32\")]",
        )
        .field_attribute(
            "nico.InstanceTypeMachineCapabilityFilterAttributes.device_type",
            "#[serde(deserialize_with = \"MachineCapabilityDeviceType::from_string\", serialize_with = \"MachineCapabilityDeviceType::serialize_from_enum_i32\")]",
        )
        .type_attribute(
            "nico.InstanceTypeMachineCapabilityFilterAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.Rack",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.RackConfig",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "nico.RackList",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.RackStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.PowerShelf", "#[derive(serde::Serialize)]")
        .type_attribute("nico.PowerShelfConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.PowerShelfList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.PowerShelfStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "common.Uint32List",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute("nico.NVLPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLPartition", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLLogicalPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLLogicalPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLLogicalPartition", "#[derive(serde::Serialize)]")
        .type_attribute("nico.NVLLogicalPartitionList", "#[derive(serde::Serialize)]")

        .type_attribute(
            "common.PowerShelfId",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            ".rack_manager",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            ".nmx_c",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "common.RouteTarget",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "common.MachineId",
            "#[derive(Ord, PartialOrd)]",
        )
        .type_attribute(
            "common.PowerShelfId",
            "#[derive(Ord, PartialOrd)]",
        )
        .type_attribute(
            "common.SwitchId",
            "#[derive(Ord, PartialOrd)]",
        )
        .type_attribute(
            "common.RemediationId",
            "#[derive(serde::Serialize, serde::Deserialize, Ord, PartialOrd)]",
        )
        .type_attribute("common.StringList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "nico.InstanceAllocationRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.RouteServerEntries",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.RouteServer",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.ComputeAllocation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.ComputeAllocationAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.GetBmcCredentialsRequest",
            "#[derive(serde::Serialize)]",
        ).type_attribute(
            "nico.PlacementInRack",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.SpdmListAttestationsResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "nico.SpdmAttestationDetails",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("nico.NicoAgentControlResponse.ScoutFirmwareUpgradeTask", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("nico.NicoAgentControlResponse.FileArtifact", "#[derive(serde::Serialize, serde::Deserialize)]")
        .build_server(true)
        .build_client(true)
        .protoc_arg("--experimental_allow_proto3_optional")
        .out_dir(autogenerated_rust_output_directory)
        .compile_protos(
            &[
                "proto/common.proto",
                "proto/nico.proto",
                "proto/dpa_rpc.proto",
                "proto/machine_discovery.proto",
                "proto/mlx_device.proto",
                "proto/nmx_c.proto",
                "proto/site_explorer.proto",
                "proto/dns.proto",
                "proto/fmds.proto",
            ],
            &["proto"],
        )
        .unwrap();

    let client_wrapper_generator = codegen::CodeGenerator::new(codegen::Config {
        wrapper_name: "NicoApiClient".to_string(),
        inner_rpc_client_type: "crate::nico_tls_client::NicoClientT".to_string(),
        proto_files: vec!["proto/nico.proto".to_string()],
        include_paths: vec!["proto".to_string()],
        generated_types_path_within_crate: "protos".to_string(),
        extern_paths: vec![
            (".common.MachineId", "::nico_uuid::machine::MachineId"),
            (".common.DomainId", "::nico_uuid::domain::DomainId"),
            (
                ".common.RemediationId",
                "::nico_uuid::dpu_remediations::RemediationId",
            ),
            (
                ".common.MachineInterfaceId",
                "::nico_uuid::machine::MachineInterfaceId",
            ),
            (".common.VpcId", "::nico_uuid::vpc::VpcId"),
            (".common.VpcPrefixId", "::nico_uuid::vpc::VpcPrefixId"),
            (
                ".common.VpcPeeringId",
                "::nico_uuid::vpc_peering::VpcPeeringId",
            ),
            (
                ".common.IBPartitionId",
                "::nico_uuid::infiniband::IBPartitionId",
            ),
            (".common.InstanceId", "::nico_uuid::instance::InstanceId"),
            (
                ".common.NetworkSegmentId",
                "::nico_uuid::network::NetworkSegmentId",
            ),
            (
                ".common.DpaInterfaceId",
                "::nico_uuid::dpa_interface::DpaInterfaceId",
            ),
            (
                ".common.NetworkPrefixId",
                "::nico_uuid::network::NetworkPrefixId",
            ),
            (".common.SwitchId", "::nico_uuid::switch::SwitchId"),
            (
                ".common.PowerShelfId",
                "::nico_uuid::power_shelf::PowerShelfId",
            ),
            (
                ".common.ComputeAllocationId",
                "::nico_uuid::compute_allocation::ComputeAllocationId",
            ),
            (
                ".common.OperatingSystemId",
                "::nico_uuid::operating_system::OperatingSystemId",
            ),
            (
                ".common.IpxeTemplateId",
                "::nico_uuid::ipxe_template::IpxeTemplateId",
            ),
            (".common.RackId", "::nico_uuid::rack::RackId"),
            (
                ".common.RackProfileId",
                "::nico_uuid::rack::RackProfileId",
            ),
            (
                ".common.NVLinkPartitionId",
                "::nico_uuid::nvlink::NvLinkPartitionId",
            ),
            (
                ".common.NVLinkLogicalPartitionId",
                "::nico_uuid::nvlink::NvLinkLogicalPartitionId",
            ),
            (
                ".common.NVLinkDomainId",
                "::nico_uuid::nvlink::NvLinkDomainId",
            ),
            (
                ".measured_boot.MeasurementSystemProfileId",
                "::nico_uuid::measured_boot::MeasurementSystemProfileId",
            ),
            (
                ".measured_boot.MeasurementSystemProfileAttrId",
                "::nico_uuid::measured_boot::MeasurementSystemProfileAttrId",
            ),
            (
                ".measured_boot.MeasurementBundleId",
                "::nico_uuid::measured_boot::MeasurementBundleId",
            ),
            (
                ".measured_boot.MeasurementBundleValueId",
                "::nico_uuid::measured_boot::MeasurementBundleValueId",
            ),
            (
                ".measured_boot.MeasurementReportId",
                "::nico_uuid::measured_boot::MeasurementReportId",
            ),
            (
                ".measured_boot.MeasurementReportValueId",
                "::nico_uuid::measured_boot::MeasurementReportValueId",
            ),
            (
                ".measured_boot.MeasurementJournalId",
                "::nico_uuid::measured_boot::MeasurementJournalId",
            ),
            (
                ".measured_boot.MeasurementApprovedMachineId",
                "::nico_uuid::measured_boot::MeasurementApprovedMachineId",
            ),
            (
                ".measured_boot.MeasurementApprovedProfileId",
                "::nico_uuid::measured_boot::MeasurementApprovedProfileId",
            ),
        ],
    })?;

    client_wrapper_generator.write_rpc_client_wrapper(out_dir.join("nico_api_client.rs"))?;
    client_wrapper_generator
        .write_rpc_convenience_converters(out_dir.join("convenience_converters.rs"))?;

    // enable the code generator for the nmx-c proto
    let nmx_c_client_wrapper = codegen::CodeGenerator::new(codegen::Config {
        wrapper_name: "NmxCApiClient".to_string(),
        inner_rpc_client_type: "crate::nico_tls_client::NmxCClientT".to_string(),
        proto_files: vec!["proto/nmx_c.proto".to_string()],
        include_paths: vec!["proto".to_string()],
        extern_paths: vec![],
        generated_types_path_within_crate: "protos".to_string(),
    })?;
    nmx_c_client_wrapper.write_rpc_client_wrapper(out_dir.join("nmx_c_client.rs"))?;
    nmx_c_client_wrapper.write_rpc_convenience_converters(out_dir.join("nmx_c_converters.rs"))?;

    Ok(())
}
