/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
use std::path::PathBuf;

use tonic_client_wrapper::codegen;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    // Write generated code to OUT_DIR rather than back into the source tree.
    // Consumers pull these in via:
    // `include!(concat!(env!("OUT_DIR"), "/X.rs"))` in `src/protos/mod.rs`
    let autogenerated_rust_output_directory = out_dir.clone();
    // The reflection path is part of the output directory (which might be debug or release),
    // so that different builds get a different binary file and concurrent builds don't collide
    let reflection = out_dir.join("core.bin");

    tonic_prost_build::configure()
        .file_descriptor_set_path(reflection)
        .type_attribute(
            ".google.protobuf.Timestamp",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            ".core.DeletedFilter",
            "#[cfg_attr(feature = \"cli\", derive(clap::ValueEnum))]",
        )
        .type_attribute(
            ".core.DpuMode",
            "#[cfg_attr(feature = \"cli\", derive(clap::ValueEnum))]",
        )
        .type_attribute(
            ".core.DpuMode",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .extern_path(".google.protobuf.Duration", "crate::Duration")
        .extern_path(".google.protobuf.Timestamp", "crate::Timestamp")
        .extern_path(".common.DomainId", "::carbide_uuid::domain::DomainId")
        .extern_path(".common.DpaInterfaceId", "::carbide_uuid::dpa_interface::DpaInterfaceId")
        .extern_path(".common.IBPartitionId", "::carbide_uuid::infiniband::IBPartitionId")
        .extern_path(".common.InstanceId", "::carbide_uuid::instance::InstanceId")
        .extern_path(".common.MachineId", "::carbide_uuid::machine::MachineId")
        .extern_path(".common.MachineInterfaceId", "::carbide_uuid::machine::MachineInterfaceId")
        .extern_path(".common.NetworkPrefixId", "::carbide_uuid::network::NetworkPrefixId")
        .extern_path(".common.NetworkSegmentId", "::carbide_uuid::network::NetworkSegmentId")
        .extern_path(".common.PowerShelfId", "::carbide_uuid::power_shelf::PowerShelfId")
        .extern_path(".common.RackId", "::carbide_uuid::rack::RackId")
        .extern_path(".common.RackProfileId", "::carbide_uuid::rack::RackProfileId")
        .extern_path(".common.NVLinkPartitionId", "::carbide_uuid::nvlink::NvLinkPartitionId")
        .extern_path(".common.NVLinkLogicalPartitionId", "::carbide_uuid::nvlink::NvLinkLogicalPartitionId")
        .extern_path(".common.NVLinkDomainId", "::carbide_uuid::nvlink::NvLinkDomainId")
        .extern_path(".common.RemediationId", "carbide_uuid::dpu_remediations::RemediationId")
        .extern_path(".common.SwitchId", "::carbide_uuid::switch::SwitchId")
        .extern_path(".common.VpcId", "::carbide_uuid::vpc::VpcId")
        .extern_path(".common.VpcPeeringId", "::carbide_uuid::vpc_peering::VpcPeeringId")
        .extern_path(".common.VpcPrefixId", "::carbide_uuid::vpc::VpcPrefixId")
        .extern_path(".common.ComputeAllocationId", "::carbide_uuid::compute_allocation::ComputeAllocationId")
        .extern_path(".common.OperatingSystemId", "::carbide_uuid::operating_system::OperatingSystemId")
        .extern_path(".common.IpxeTemplateId", "::carbide_uuid::ipxe_template::IpxeTemplateId")
        .extern_path(".common.MachineValidationId", "::carbide_uuid::machine_validation::MachineValidationId")
        .extern_path(".measured_boot.MeasurementSystemProfileId", "::carbide_uuid::measured_boot::MeasurementSystemProfileId")
        .extern_path(".measured_boot.MeasurementSystemProfileAttrId", "::carbide_uuid::measured_boot::MeasurementSystemProfileAttrId")
        .extern_path(".measured_boot.MeasurementBundleId", "::carbide_uuid::measured_boot::MeasurementBundleId")
        .extern_path(".measured_boot.MeasurementBundleValueId", "::carbide_uuid::measured_boot::MeasurementBundleValueId")
        .extern_path(".measured_boot.MeasurementReportId", "::carbide_uuid::measured_boot::MeasurementReportId")
        .extern_path(".measured_boot.MeasurementReportValueId", "::carbide_uuid::measured_boot::MeasurementReportValueId")
        .extern_path(".measured_boot.MeasurementJournalId", "::carbide_uuid::measured_boot::MeasurementJournalId")
        .extern_path(".measured_boot.MeasurementApprovedMachineId", "::carbide_uuid::measured_boot::MeasurementApprovedMachineId")
        .extern_path(".measured_boot.MeasurementApprovedProfileId", "::carbide_uuid::measured_boot::MeasurementApprovedProfileId")
        .include_file("prost_common.rs")
        .type_attribute(".health", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            ".machine_discovery",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            ".site_explorer",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            ".mlx_device",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.AdminForceDeleteMachineRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.AdminForceDeleteMachineResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.ClientSecretBasic", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(".dns", "#[derive(serde::Serialize)]")
        .type_attribute("core.FabricManagerConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.FabricManagerStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.FlatInterfaceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.FlatInterfaceIpv6Config", "#[derive(serde::Serialize)]")
        .type_attribute("core.InstanceInterfaceIpv6Config", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "core.InstanceInterfaceConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.InstanceInterfaceConfig.network_details",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.InstanceIBInterfaceConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("core.InstanceUpdateStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.InstanceNetworkConfig", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.InstanceInfinibandConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("core.InstanceStorageConfig", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.IpxeTemplateParameter",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.IpxeTemplateArtifact",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.IpxeTemplate",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.IpxeTemplateArtifactCacheStrategy",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("core.TenantConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.InstanceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.InstanceDpuExtensionServicesConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.InstanceDpuExtensionServiceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.ManagedHostDpuExtensionServiceConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.DpuExtensionService", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceVersionInfo", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceType", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceIdList", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceCredential", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceCredential.type", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.UsernamePassword", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceStatusObservation", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceComponent", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceStatus", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceObservability", "#[derive(serde::Serialize, serde::Deserialize)]")        
        .type_attribute("core.DpuExtensionServiceObservabilityConfigPrometheus", "#[derive(serde::Serialize, serde::Deserialize)]") 
        .type_attribute("core.DpuExtensionServiceObservabilityConfigLogging", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceObservabilityConfig.config", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceObservabilityConfig", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.DpuExtensionServiceObservability.configs", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.InstanceNVLinkConfig", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("core.InstanceNVLinkGpuConfig", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("core.InstanceNVLinkStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.InstanceNVLinkGpuStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkPartition", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkPartitionGpuStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkLogicalPartition", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkLogicalPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkLogicalPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkLogicalPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkLogicalPartitionGpuStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.MachineNVLinkGpuStatusObservation", "#[derive(serde::Serialize)]")
        .type_attribute("core.MachineNVLinkStatusObservation", "#[derive(serde::Serialize)]")
        .type_attribute("common.NVLinkDomainId", "#[derive(serde::Serialize)]")
        .type_attribute("core.NvlinkNmxcEndpoint", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("core.NvlinkNmxcEndpointList", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "core.DeleteNvlinkNmxcEndpointRequest",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("common.NVLinkLogicalPartitionId", "#[derive(serde::Serialize)]")
        .type_attribute("common.NVLinkPartitionId", "#[derive(serde::Serialize)]")
        .type_attribute("core.MachineNVLinkInfo", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLinkGpu", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.InstanceInterfaceStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.InstanceIBInterfaceStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.InstanceNetworkStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.InstanceInfinibandStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.InstanceStorageStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.InstanceDpuExtensionServicesStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.InstanceDpuExtensionServiceStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.InstanceTenantStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.InstanceStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.Instance", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.Metadata",
            "#[derive(serde::Serialize, serde::Deserialize, Eq)]",
        )
        .type_attribute(
            "core.Label",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "core.LifecycleStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.InstancePhoneHomeLastContactRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.InstancePhoneHomeLastContactResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.InstanceList", "#[derive(serde::Serialize)]")
        .type_attribute("core.Machine", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.MachineCapabilitiesSet",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.MachineCapabilityAttributesCpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.MachineCapabilityAttributesGpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.MachineCapabilityAttributesMemory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.MachineCapabilityAttributesStorage",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.MachineCapabilityAttributesNetwork",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.MachineCapabilityAttributesInfiniband",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.MachineCapabilityAttributesDpu",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.MachineList", "#[derive(serde::Serialize)]")
        .type_attribute("core.MachineEvent", "#[derive(serde::Serialize)]")
        .type_attribute("core.MachineInterface", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.InfinibandStatusObservation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.MachineIbInterface", "#[derive(serde::Serialize)]")
        .type_attribute("core.MachineState", "#[derive(serde::Serialize)]")
        .type_attribute("core.MachineArchitecture", "#[derive(serde::Serialize)]")
        .type_attribute("core.MachineInventory", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.MachineInventorySoftwareComponent",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.HealthReportEntry", "#[derive(serde::Serialize)]")
        .type_attribute("core.HealthSourceOrigin", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            "core.ManagedHostNetworkConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.ManagedHostNetworkConfigResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.RoutingProfile",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.PrefixFilterPolicyEntry",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.TrafficInterceptConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.TrafficInterceptBridging", "#[derive(serde::Serialize)]")
        .type_attribute("core.NetworkPrefix", "#[derive(serde::Serialize)]")
        .type_attribute("core.NetworkPrefixEvent", "#[derive(serde::Serialize)]")
        .type_attribute("core.NetworkSegmentConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.NetworkSegmentStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.NetworkSegment", "#[derive(serde::Serialize)]")
        .type_attribute("core.IBPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.IBPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.IBPartition", "#[derive(serde::Serialize)]")
        .type_attribute("core.IBPartitionIdList", "#[derive(serde::Serialize)]")
        .type_attribute("core.IBPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("core.PowerOptionResponse",
                        "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("core.PowerOptions",
                        "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            "core.InlineIpxe",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("core.NetworkSegmentList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.InstanceOperatingSystemConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.InstanceOperatingSystemConfig.variant",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.OperatingSystem",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "core.OperatingSystemList",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "core.OperatingSystemType",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("core.InterfaceList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.NetworkSegmentStateHistory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.RackStateHistory",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.Tenant", "#[derive(serde::Serialize)]")
        .type_attribute("core.TenantContent", "#[derive(serde::Serialize)]")
        .type_attribute("core.TenantList", "#[derive(serde::Serialize)]")
        .type_attribute("core.TenantKeyset", "#[derive(serde::Serialize)]")
        .type_attribute("core.TenantKeysetContent", "#[derive(serde::Serialize)]")
        .type_attribute("core.TenantKeysetList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.TenantKeysetIdentifier",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.TenantPublicKey", "#[derive(serde::Serialize)]")
        .type_attribute("core.TenantKeySetList", "#[derive(serde::Serialize)]")
        .type_attribute("core.VpcResourceState", "#[derive(serde::Serialize)]")
        .type_attribute("core.MachineBootOverride", "#[derive(serde::Serialize)]")
        .type_attribute("core.ConnectedDevice", "#[derive(serde::Serialize)]")
        .type_attribute("core.NetworkDevice", "#[derive(serde::Serialize)]")
        .type_attribute("core.NetworkTopologyData", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.InstanceInterfaceStatusObservation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.FabricInterfaceData", "#[derive(serde::Serialize)]")
        .type_attribute("core.LinkData", "#[derive(serde::Serialize)]")
        .type_attribute("core.DpuNetworkStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.LastDhcpRequest", "#[derive(serde::Serialize)]")
        .type_attribute("core.ResourcePool", "#[derive(serde::Serialize)]")
        .type_attribute("core.DpaInterface", "#[derive(serde::Serialize)]")
        .type_attribute("core.DpaInterfaceList", "#[derive(serde::Serialize)]")
        .type_attribute("core.Vpc", "#[derive(serde::Serialize)]")
        .type_attribute("core.VpcStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.VpcList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.StorageClusterAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.VpcPrefix", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.VpcPrefixConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.VpcPrefixStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.VpcPeering", "#[derive(serde::Serialize)]")
        .type_attribute("core.VpcPeeringList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.StateHistoryRecord",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.StorageCluster", "#[derive(serde::Serialize)]")
        .type_attribute("core.StoragePoolAttributes", "#[derive(serde::Serialize)]")
        .type_attribute("core.StoragePool", "#[derive(serde::Serialize)]")
        .type_attribute("core.StorageVolumeStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.StorageVolumeAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.StorageVolume", "#[derive(serde::Serialize)]")
        .type_attribute("core.Switch", "#[derive(serde::Serialize)]")
        .type_attribute("core.SwitchConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.SwitchList", "#[derive(serde::Serialize)]")
        .type_attribute("core.SwitchStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.DeleteStoragePoolRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.ListStoragePoolRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.ListStoragePoolResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.DeleteStorageVolumeRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.ListStorageVolumeRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.ListStorageVolumeResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.OsImageAttributes", "#[derive(serde::Serialize)]")
        .type_attribute("core.OsImage", "#[derive(serde::Serialize)]")
        .type_attribute("core.ListOsImageRequest", "#[derive(serde::Serialize)]")
        .type_attribute("core.ListOsImageResponse", "#[derive(serde::Serialize)]")
        .type_attribute("DeleteOsImageRequest", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.MachineDiscoveryInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "common.UUID",
            "#[derive(Ord, PartialOrd, serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.MachineDiscoveryInfo.discovery_data",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.DhcpDiscovery",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.UserRoles",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.BMCRequestType",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "core.BmcInfo",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "core.bmc_meta_data_update_request.DataItem",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "DataItem",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "bmc_meta_data_update_request",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "BMCMetaDataUpdateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "ControllerStateReason",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("ControllerStateSourceReference", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute(
            "RuntimeConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("StateSla", "#[derive(serde::Serialize)]")
        .type_attribute(
            "BuildInfo",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("MachineValidationResultList", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationResult", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationRunList", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationRun", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedHostNic", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedHostNic", "#[derive(serde::Deserialize)]")
        .type_attribute("HostLifecycleProfile", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute("ExpectedMachine", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedPowerShelf", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedSwitch", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedRack", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedMachineList", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedPowerShelfList", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedSwitchList", "#[derive(serde::Serialize)]")
        .type_attribute("ExpectedRackList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "TpmCaCertDetail",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaCertDetailCollection",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmEkCertStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmEkCertStatusCollection",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaAddedCaStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "TpmCaCertId",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("MachineValidationState", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationCompleted", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationInProgress", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationStarted", "#[derive(serde::Serialize)]")
        .type_attribute("MachineValidationStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "MachineValidationExternalConfig",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestUpdateRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestAddRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestsGetRequest",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "MachineValidationTestUpdateRequest.Payload",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.RedfishBrowseResponse",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroup",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupSource",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupRuleDirection",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupRuleProtocol",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupRuleAction",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupRuleAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .field_attribute(
            "core.NetworkSecurityGroupRuleAttributes.direction",
            "#[serde(deserialize_with = \"NetworkSecurityGroupRuleDirection::from_string\", serialize_with = \"NetworkSecurityGroupRuleDirection::serialize_from_enum_i32\")]",
        )
        .field_attribute(
            "core.NetworkSecurityGroupRuleAttributes.protocol",
            "#[serde(deserialize_with = \"NetworkSecurityGroupRuleProtocol::from_string\", serialize_with = \"NetworkSecurityGroupRuleProtocol::serialize_from_enum_i32\")]",
        )
        .field_attribute(
            "core.NetworkSecurityGroupRuleAttributes.action",
            "#[serde(deserialize_with = \"NetworkSecurityGroupRuleAction::from_string\", serialize_with = \"NetworkSecurityGroupRuleAction::serialize_from_enum_i32\")]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupRuleAttributes.source_net",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupRuleAttributes.source_net",
            "#[serde(rename_all=\"snake_case\")]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupRuleAttributes.destination_net",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupRuleAttributes.destination_net",
            "#[serde(rename_all=\"snake_case\")]",
        )
        .type_attribute(
            "core.InstanceNetworkRestrictions",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.FlatInterfaceNetworkSecurityGroupConfig",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.ResolvedNetworkSecurityGroupRule",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupAttachments",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.NetworkSecurityGroupPropagationObjectStatus",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("Sku", "#[derive(serde::Serialize, serde::Deserialize)]")
        .field_attribute("Sku.schema_version", "#[serde(default)]")
        .field_attribute("Sku.associated_machine_ids", "#[serde(default)]")
        .type_attribute("SkuList", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "SkuComponents",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentChassis",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentCpu",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "common.SwitchId",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "SkuComponentGpu",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentMemory",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentInfinibandDevices",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentEthernetDevices",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "SkuComponentStorage",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .field_attribute("SkuComponentStorage.vendor", "#[serde(default)]")
        .field_attribute("SkuComponentStorage.capacity_mb", "#[serde(default)]")
        .type_attribute(
            "SkuComponentTpm",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("SkuId", "#[derive(serde::Serialize, serde::Deserialize)]")
        .type_attribute(
            "SkuStatus",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute("core.RackFirmware", "#[derive(serde::Serialize)]")
        .type_attribute("core.RackFirmwareList", "#[derive(serde::Serialize)]")
        .type_attribute("core.RackFirmwareHistoryRecord", "#[derive(serde::Serialize)]")
        .type_attribute("core.RackFirmwareHistoryRecords", "#[derive(serde::Serialize)]")
        .type_attribute("core.RackFirmwareHistoryResponse", "#[derive(serde::Serialize)]")
        .type_attribute("common.RackHardwareType", "#[derive(serde::Serialize)]")
        .type_attribute("core.RackCapabilitiesSet", "#[derive(serde::Serialize)]")
        .type_attribute("core.RackCapabilityCompute", "#[derive(serde::Serialize)]")
        .type_attribute("core.RackCapabilitySwitch", "#[derive(serde::Serialize)]")
        .type_attribute("core.RackCapabilityPowerShelf", "#[derive(serde::Serialize)]")
        .type_attribute("core.RackProfile", "#[derive(serde::Serialize)]")
        .type_attribute("core.GetRackProfileResponse", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.MachineHardwareInfoGpu",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.ManagedHostQuarantineState",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "core.ManagedHostQuarantineMode",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute("core.AppliedRemediationIdList", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("core.AppliedRemediationId", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("core.AppliedRemediationList", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("core.AppliedRemediation", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("core.RemediationList", "#[derive(serde::Deserialize, serde::Serialize)]")
        .type_attribute("core.Remediation", "#[derive(serde::Deserialize, serde::Serialize)]")
        .field_attribute("machine_discovery.BlockDevice.device_type", "#[serde(default)]")
        .field_attribute("machine_discovery.NvmeDevice.serial", "#[serde(default)]")
        .type_attribute(
            "core.InstanceTypeAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.InstanceType",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.InstanceTypeAllocationStats",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .field_attribute(
            "core.InstanceTypeMachineCapabilityFilterAttributes.capability_type",
            "#[serde(deserialize_with = \"MachineCapabilityType::from_string\", serialize_with = \"MachineCapabilityType::serialize_from_enum_i32\")]",
        )
        .field_attribute(
            "core.InstanceTypeMachineCapabilityFilterAttributes.device_type",
            "#[serde(deserialize_with = \"MachineCapabilityDeviceType::from_string\", serialize_with = \"MachineCapabilityDeviceType::serialize_from_enum_i32\")]",
        )
        .type_attribute(
            "core.InstanceTypeMachineCapabilityFilterAttributes",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.Rack",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.RackConfig",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "core.RackList",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.RackStatus",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.PowerShelf", "#[derive(serde::Serialize)]")
        .type_attribute("core.PowerShelfConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.PowerShelfList", "#[derive(serde::Serialize)]")
        .type_attribute("core.PowerShelfStatus", "#[derive(serde::Serialize)]")
        .type_attribute(
            "common.Uint32List",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute("core.NVLPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLPartition", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLPartitionList", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLLogicalPartitionConfig", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLLogicalPartitionStatus", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLLogicalPartition", "#[derive(serde::Serialize)]")
        .type_attribute("core.NVLLogicalPartitionList", "#[derive(serde::Serialize)]")

        .type_attribute(
            "common.PowerShelfId",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            ".rack_manager",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            ".nmx_c",
            "#[derive(serde::Deserialize, serde::Serialize)]",
        )
        .type_attribute(
            "common.RouteTarget",
            "#[derive(serde::Deserialize,serde::Serialize)]",
        )
        .type_attribute(
            "common.MachineId",
            "#[derive(Ord, PartialOrd)]",
        )
        .type_attribute(
            "common.PowerShelfId",
            "#[derive(Ord, PartialOrd)]",
        )
        .type_attribute(
            "common.SwitchId",
            "#[derive(Ord, PartialOrd)]",
        )
        .type_attribute(
            "common.RemediationId",
            "#[derive(serde::Serialize, serde::Deserialize, Ord, PartialOrd)]",
        )
        .type_attribute("common.StringList", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.InstanceAllocationRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.RouteServerEntries",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.RouteServer",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.ComputeAllocation",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.ComputeAllocationAttributes",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.GetBmcCredentialsRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.GetSwitchNvosCredentialsRequest",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute("core.SwitchNvosInfo", "#[derive(serde::Serialize)]")
        .type_attribute(
            "core.PlacementInRack",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.SpdmListAttestationsResponse",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "core.SpdmAttestationDetails",
            "#[derive(serde::Serialize)]",
        )
        .type_attribute(
            "scout_firmware_upgrade.ScoutFirmwareUpgradeTask",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .type_attribute(
            "scout_firmware_upgrade.FileArtifact",
            "#[derive(serde::Serialize, serde::Deserialize)]",
        )
        .build_server(true)
        .build_client(true)
        .protoc_arg("--experimental_allow_proto3_optional")
        .out_dir(autogenerated_rust_output_directory)
        .compile_protos(
            &[
                "proto/common.proto",
                "proto/scout_firmware_upgrade.proto",
                "proto/core.proto",
                "proto/machine_discovery.proto",
                "proto/mlx_device.proto",
                "proto/nmx_c.proto",
                "proto/site_explorer.proto",
                "proto/dns.proto",
                "proto/fmds.proto",
            ],
            &["proto"],
        )
        .unwrap();

    let client_wrapper_generator = codegen::CodeGenerator::new(codegen::Config {
        wrapper_name: "ForgeApiClient".to_string(),
        inner_rpc_client_type: "crate::forge_tls_client::ForgeClientT".to_string(),
        proto_files: vec!["proto/core.proto".to_string()],
        include_paths: vec!["proto".to_string()],
        generated_types_path_within_crate: "protos".to_string(),
        extern_paths: vec![
            (".common.MachineId", "::carbide_uuid::machine::MachineId"),
            (".common.DomainId", "::carbide_uuid::domain::DomainId"),
            (
                ".common.RemediationId",
                "::carbide_uuid::dpu_remediations::RemediationId",
            ),
            (
                ".common.MachineInterfaceId",
                "::carbide_uuid::machine::MachineInterfaceId",
            ),
            (".common.VpcId", "::carbide_uuid::vpc::VpcId"),
            (".common.VpcPrefixId", "::carbide_uuid::vpc::VpcPrefixId"),
            (
                ".common.VpcPeeringId",
                "::carbide_uuid::vpc_peering::VpcPeeringId",
            ),
            (
                ".common.IBPartitionId",
                "::carbide_uuid::infiniband::IBPartitionId",
            ),
            (".common.InstanceId", "::carbide_uuid::instance::InstanceId"),
            (
                ".common.NetworkSegmentId",
                "::carbide_uuid::network::NetworkSegmentId",
            ),
            (
                ".common.DpaInterfaceId",
                "::carbide_uuid::dpa_interface::DpaInterfaceId",
            ),
            (
                ".common.NetworkPrefixId",
                "::carbide_uuid::network::NetworkPrefixId",
            ),
            (".common.SwitchId", "::carbide_uuid::switch::SwitchId"),
            (
                ".common.PowerShelfId",
                "::carbide_uuid::power_shelf::PowerShelfId",
            ),
            (
                ".common.ComputeAllocationId",
                "::carbide_uuid::compute_allocation::ComputeAllocationId",
            ),
            (
                ".common.OperatingSystemId",
                "::carbide_uuid::operating_system::OperatingSystemId",
            ),
            (
                ".common.IpxeTemplateId",
                "::carbide_uuid::ipxe_template::IpxeTemplateId",
            ),
            (".common.RackId", "::carbide_uuid::rack::RackId"),
            (
                ".common.RackProfileId",
                "::carbide_uuid::rack::RackProfileId",
            ),
            (
                ".common.NVLinkPartitionId",
                "::carbide_uuid::nvlink::NvLinkPartitionId",
            ),
            (
                ".common.NVLinkLogicalPartitionId",
                "::carbide_uuid::nvlink::NvLinkLogicalPartitionId",
            ),
            (
                ".common.NVLinkDomainId",
                "::carbide_uuid::nvlink::NvLinkDomainId",
            ),
            (
                ".measured_boot.MeasurementSystemProfileId",
                "::carbide_uuid::measured_boot::MeasurementSystemProfileId",
            ),
            (
                ".measured_boot.MeasurementSystemProfileAttrId",
                "::carbide_uuid::measured_boot::MeasurementSystemProfileAttrId",
            ),
            (
                ".measured_boot.MeasurementBundleId",
                "::carbide_uuid::measured_boot::MeasurementBundleId",
            ),
            (
                ".measured_boot.MeasurementBundleValueId",
                "::carbide_uuid::measured_boot::MeasurementBundleValueId",
            ),
            (
                ".measured_boot.MeasurementReportId",
                "::carbide_uuid::measured_boot::MeasurementReportId",
            ),
            (
                ".measured_boot.MeasurementReportValueId",
                "::carbide_uuid::measured_boot::MeasurementReportValueId",
            ),
            (
                ".measured_boot.MeasurementJournalId",
                "::carbide_uuid::measured_boot::MeasurementJournalId",
            ),
            (
                ".measured_boot.MeasurementApprovedMachineId",
                "::carbide_uuid::measured_boot::MeasurementApprovedMachineId",
            ),
            (
                ".measured_boot.MeasurementApprovedProfileId",
                "::carbide_uuid::measured_boot::MeasurementApprovedProfileId",
            ),
        ],
    })?;

    client_wrapper_generator.write_rpc_client_wrapper(out_dir.join("forge_api_client.rs"))?;
    client_wrapper_generator
        .write_rpc_convenience_converters(out_dir.join("convenience_converters.rs"))?;

    // enable the code generator for the nmx-c proto
    let nmx_c_client_wrapper = codegen::CodeGenerator::new(codegen::Config {
        wrapper_name: "NmxCApiClient".to_string(),
        inner_rpc_client_type: "crate::forge_tls_client::NmxCClientT".to_string(),
        proto_files: vec!["proto/nmx_c.proto".to_string()],
        include_paths: vec!["proto".to_string()],
        extern_paths: vec![],
        generated_types_path_within_crate: "protos".to_string(),
    })?;
    nmx_c_client_wrapper.write_rpc_client_wrapper(out_dir.join("nmx_c_client.rs"))?;
    nmx_c_client_wrapper.write_rpc_convenience_converters(out_dir.join("nmx_c_converters.rs"))?;

    Ok(())
}
