### DPF contract ###
serviceDaemonSet:
  nodeSelector:
  labels: {}
  annotations: {}
  updateStrategy: {}
  resources: {}
exposedPorts:
  labels: {}
  ports: {}

### Cert directory + root CA filename overrides.
certsDir: /opt/nico
rootCaFile: nico_root.pem

### Service specific values ###
image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []
podSecurityContext: {}
securityContext: {}
tolerations: []
